// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/admin/balance_admin_service.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceAdminService_GetWallet_FullMethodName      = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService/GetWallet"
	BalanceAdminService_GetTransaction_FullMethodName = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService/GetTransaction"
	BalanceAdminService_PostAdjustment_FullMethodName = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService/PostAdjustment"
	BalanceAdminService_ListTopUps_FullMethodName     = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService/ListTopUps"
	BalanceAdminService_ConfirmTopUp_FullMethodName   = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService/ConfirmTopUp"
)

// BalanceAdminServiceClient is the client API for BalanceAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceAdminServiceClient interface {
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	PostAdjustment(ctx context.Context, in *PostAdjustmentRequest, opts ...grpc.CallOption) (*PostAdjustmentResponse, error)
	ListTopUps(ctx context.Context, in *ListTopUpsRequest, opts ...grpc.CallOption) (*ListTopUpsResponse, error)
	ConfirmTopUp(ctx context.Context, in *ConfirmTopUpRequest, opts ...grpc.CallOption) (*ConfirmTopUpResponse, error)
}

type balanceAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceAdminServiceClient(cc grpc.ClientConnInterface) BalanceAdminServiceClient {
	return &balanceAdminServiceClient{cc}
}

func (c *balanceAdminServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, BalanceAdminService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdminServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, BalanceAdminService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdminServiceClient) PostAdjustment(ctx context.Context, in *PostAdjustmentRequest, opts ...grpc.CallOption) (*PostAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostAdjustmentResponse)
	err := c.cc.Invoke(ctx, BalanceAdminService_PostAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdminServiceClient) ListTopUps(ctx context.Context, in *ListTopUpsRequest, opts ...grpc.CallOption) (*ListTopUpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopUpsResponse)
	err := c.cc.Invoke(ctx, BalanceAdminService_ListTopUps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceAdminServiceClient) ConfirmTopUp(ctx context.Context, in *ConfirmTopUpRequest, opts ...grpc.CallOption) (*ConfirmTopUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmTopUpResponse)
	err := c.cc.Invoke(ctx, BalanceAdminService_ConfirmTopUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceAdminServiceServer is the server API for BalanceAdminService service.
// All implementations must embed UnimplementedBalanceAdminServiceServer
// for forward compatibility.
type BalanceAdminServiceServer interface {
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	PostAdjustment(context.Context, *PostAdjustmentRequest) (*PostAdjustmentResponse, error)
	ListTopUps(context.Context, *ListTopUpsRequest) (*ListTopUpsResponse, error)
	ConfirmTopUp(context.Context, *ConfirmTopUpRequest) (*ConfirmTopUpResponse, error)
	mustEmbedUnimplementedBalanceAdminServiceServer()
}

// UnimplementedBalanceAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceAdminServiceServer struct{}

func (UnimplementedBalanceAdminServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedBalanceAdminServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedBalanceAdminServiceServer) PostAdjustment(context.Context, *PostAdjustmentRequest) (*PostAdjustmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAdjustment not implemented")
}
func (UnimplementedBalanceAdminServiceServer) ListTopUps(context.Context, *ListTopUpsRequest) (*ListTopUpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopUps not implemented")
}
func (UnimplementedBalanceAdminServiceServer) ConfirmTopUp(context.Context, *ConfirmTopUpRequest) (*ConfirmTopUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTopUp not implemented")
}
func (UnimplementedBalanceAdminServiceServer) mustEmbedUnimplementedBalanceAdminServiceServer() {}
func (UnimplementedBalanceAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeBalanceAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceAdminServiceServer will
// result in compilation errors.
type UnsafeBalanceAdminServiceServer interface {
	mustEmbedUnimplementedBalanceAdminServiceServer()
}

func RegisterBalanceAdminServiceServer(s grpc.ServiceRegistrar, srv BalanceAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedBalanceAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceAdminService_ServiceDesc, srv)
}

func _BalanceAdminService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdminServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdminService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdminServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdminService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdminServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdminService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdminServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdminService_PostAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdminServiceServer).PostAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdminService_PostAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdminServiceServer).PostAdjustment(ctx, req.(*PostAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdminService_ListTopUps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopUpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdminServiceServer).ListTopUps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdminService_ListTopUps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdminServiceServer).ListTopUps(ctx, req.(*ListTopUpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceAdminService_ConfirmTopUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTopUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceAdminServiceServer).ConfirmTopUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceAdminService_ConfirmTopUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceAdminServiceServer).ConfirmTopUp(ctx, req.(*ConfirmTopUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceAdminService_ServiceDesc is the grpc.ServiceDesc for BalanceAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService",
	HandlerType: (*BalanceAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWallet",
			Handler:    _BalanceAdminService_GetWallet_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _BalanceAdminService_GetTransaction_Handler,
		},
		{
			MethodName: "PostAdjustment",
			Handler:    _BalanceAdminService_PostAdjustment_Handler,
		},
		{
			MethodName: "ListTopUps",
			Handler:    _BalanceAdminService_ListTopUps_Handler,
		},
		{
			MethodName: "ConfirmTopUp",
			Handler:    _BalanceAdminService_ConfirmTopUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/admin/balance_admin_service.proto",
}
