// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/admin/balance_admin_service.proto

package admin

import (
	domain "github.com/martketplace-vkr/balance/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     domain.WalletOwnerType `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType" json:"owner_type,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletRequest) GetOwnerType() domain.WalletOwnerType {
	if x != nil {
		return x.OwnerType
	}
	return domain.WalletOwnerType(0)
}

func (x *GetWalletRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *domain.Wallet         `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletResponse) GetWallet() *domain.Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type PostAdjustmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerType      domain.WalletOwnerType `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType" json:"owner_type,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostAdjustmentRequest) Reset() {
	*x = PostAdjustmentRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAdjustmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAdjustmentRequest) ProtoMessage() {}

func (x *PostAdjustmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAdjustmentRequest.ProtoReflect.Descriptor instead.
func (*PostAdjustmentRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *PostAdjustmentRequest) GetOwnerType() domain.WalletOwnerType {
	if x != nil {
		return x.OwnerType
	}
	return domain.WalletOwnerType(0)
}

func (x *PostAdjustmentRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *PostAdjustmentRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *PostAdjustmentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PostAdjustmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PostAdjustmentResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAdjustmentResponse) Reset() {
	*x = PostAdjustmentResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAdjustmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAdjustmentResponse) ProtoMessage() {}

func (x *PostAdjustmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAdjustmentResponse.ProtoReflect.Descriptor instead.
func (*PostAdjustmentResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *PostAdjustmentResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_v1_admin_balance_admin_service_proto protoreflect.FileDescriptor

const file_v1_admin_balance_admin_service_proto_rawDesc = "" +
	"\n" +
	"$v1/admin/balance_admin_service.proto\x129github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin\x1a\x1ev1/domain/balance_domain.proto\"\x99\x01\n" +
	"\x10GetWalletRequest\x12j\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerTypeR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\"o\n" +
	"\x11GetWalletResponse\x12Z\n" +
	"\x06wallet\x18\x01 \x01(\v2B.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletR\x06wallet\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"\x89\x01\n" +
	"\x16GetTransactionResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction\"\xb8\x02\n" +
	"\x15PostAdjustmentRequest\x12j\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerTypeR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x89\x01\n" +
	"\x16PostAdjustmentResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction2\xae\x04\n" +
	"\x13BalanceAdminService\x12\xa6\x01\n" +
	"\tGetWallet\x12K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest\x1aL.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse\x12\xb5\x01\n" +
	"\x0eGetTransaction\x12P.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionRequest\x1aQ.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse\x12\xb5\x01\n" +
	"\x0ePostAdjustment\x12P.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest\x1aQ.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponseBAZ?github.com/martketplace-vkr/balance/pkg/api/grpc/v1/admin;adminb\x06proto3"

var (
	file_v1_admin_balance_admin_service_proto_rawDescOnce sync.Once
	file_v1_admin_balance_admin_service_proto_rawDescData []byte
)

func file_v1_admin_balance_admin_service_proto_rawDescGZIP() []byte {
	file_v1_admin_balance_admin_service_proto_rawDescOnce.Do(func() {
		file_v1_admin_balance_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_balance_admin_service_proto_rawDesc), len(file_v1_admin_balance_admin_service_proto_rawDesc)))
	})
	return file_v1_admin_balance_admin_service_proto_rawDescData
}

var file_v1_admin_balance_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_admin_balance_admin_service_proto_goTypes = []any{
	(*GetWalletRequest)(nil),         // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest
	(*GetWalletResponse)(nil),        // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse
	(*GetTransactionRequest)(nil),    // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionRequest
	(*GetTransactionResponse)(nil),   // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse
	(*PostAdjustmentRequest)(nil),    // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest
	(*PostAdjustmentResponse)(nil),   // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponse
	(domain.WalletOwnerType)(0),      // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	(*domain.Wallet)(nil),            // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet
	(*domain.LedgerTransaction)(nil), // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	(*domain.Money)(nil),             // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
}
var file_v1_admin_balance_admin_service_proto_depIdxs = []int32{
	6, // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest.owner_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	7, // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse.wallet:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet
	8, // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	6, // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest.owner_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	9, // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	8, // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	0, // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetWallet:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest
	2, // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetTransaction:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionRequest
	4, // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.PostAdjustment:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest
	1, // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetWallet:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse
	3, // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetTransaction:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse
	5, // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.PostAdjustment:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_v1_admin_balance_admin_service_proto_init() }
func file_v1_admin_balance_admin_service_proto_init() {
	if File_v1_admin_balance_admin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_balance_admin_service_proto_rawDesc), len(file_v1_admin_balance_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_balance_admin_service_proto_goTypes,
		DependencyIndexes: file_v1_admin_balance_admin_service_proto_depIdxs,
		MessageInfos:      file_v1_admin_balance_admin_service_proto_msgTypes,
	}.Build()
	File_v1_admin_balance_admin_service_proto = out.File
	file_v1_admin_balance_admin_service_proto_goTypes = nil
	file_v1_admin_balance_admin_service_proto_depIdxs = nil
}
