// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/admin/balance_admin_service.proto

package admin

import (
	domain "github.com/martketplace-vkr/balance/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     domain.WalletOwnerType `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType" json:"owner_type,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletRequest) GetOwnerType() domain.WalletOwnerType {
	if x != nil {
		return x.OwnerType
	}
	return domain.WalletOwnerType(0)
}

func (x *GetWalletRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *domain.Wallet         `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletResponse) GetWallet() *domain.Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type GetWalletTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     domain.WalletOwnerType `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType" json:"owner_type,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CurrencyCode  *int64                 `protobuf:"varint,3,opt,name=currency_code,json=currencyCode,proto3,oneof" json:"currency_code,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletTransactionsRequest) Reset() {
	*x = GetWalletTransactionsRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTransactionsRequest) ProtoMessage() {}

func (x *GetWalletTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetWalletTransactionsRequest) GetOwnerType() domain.WalletOwnerType {
	if x != nil {
		return x.OwnerType
	}
	return domain.WalletOwnerType(0)
}

func (x *GetWalletTransactionsRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetCurrencyCode() int64 {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetWalletTransactionsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Transactions  []*domain.LedgerTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletTransactionsResponse) Reset() {
	*x = GetWalletTransactionsResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTransactionsResponse) ProtoMessage() {}

func (x *GetWalletTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetWalletTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletTransactionsResponse) GetTransactions() []*domain.LedgerTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type PostAdjustmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerType      domain.WalletOwnerType `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType" json:"owner_type,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostAdjustmentRequest) Reset() {
	*x = PostAdjustmentRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAdjustmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAdjustmentRequest) ProtoMessage() {}

func (x *PostAdjustmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAdjustmentRequest.ProtoReflect.Descriptor instead.
func (*PostAdjustmentRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *PostAdjustmentRequest) GetOwnerType() domain.WalletOwnerType {
	if x != nil {
		return x.OwnerType
	}
	return domain.WalletOwnerType(0)
}

func (x *PostAdjustmentRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *PostAdjustmentRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *PostAdjustmentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PostAdjustmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PostAdjustmentResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostAdjustmentResponse) Reset() {
	*x = PostAdjustmentResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostAdjustmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAdjustmentResponse) ProtoMessage() {}

func (x *PostAdjustmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAdjustmentResponse.ProtoReflect.Descriptor instead.
func (*PostAdjustmentResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *PostAdjustmentResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ListTopUpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  *int64                 `protobuf:"varint,1,opt,name=currency_code,json=currencyCode,proto3,oneof" json:"currency_code,omitempty"`
	ProviderType  *domain.ProviderType   `protobuf:"varint,2,opt,name=provider_type,json=providerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType,oneof" json:"provider_type,omitempty"`
	Status        *domain.TopUpStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatus,oneof" json:"status,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopUpsRequest) Reset() {
	*x = ListTopUpsRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopUpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopUpsRequest) ProtoMessage() {}

func (x *ListTopUpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopUpsRequest.ProtoReflect.Descriptor instead.
func (*ListTopUpsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListTopUpsRequest) GetCurrencyCode() int64 {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return 0
}

func (x *ListTopUpsRequest) GetProviderType() domain.ProviderType {
	if x != nil && x.ProviderType != nil {
		return *x.ProviderType
	}
	return domain.ProviderType(0)
}

func (x *ListTopUpsRequest) GetStatus() domain.TopUpStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return domain.TopUpStatus(0)
}

func (x *ListTopUpsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTopUpsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTopUpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopUps        []*domain.TopUp        `protobuf:"bytes,1,rep,name=top_ups,json=topUps,proto3" json:"top_ups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopUpsResponse) Reset() {
	*x = ListTopUpsResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopUpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopUpsResponse) ProtoMessage() {}

func (x *ListTopUpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopUpsResponse.ProtoReflect.Descriptor instead.
func (*ListTopUpsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListTopUpsResponse) GetTopUps() []*domain.TopUp {
	if x != nil {
		return x.TopUps
	}
	return nil
}

type ConfirmTopUpRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalId     string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ProviderName   string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	WebhookEventId string                 `protobuf:"bytes,4,opt,name=webhook_event_id,json=webhookEventId,proto3" json:"webhook_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfirmTopUpRequest) Reset() {
	*x = ConfirmTopUpRequest{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTopUpRequest) ProtoMessage() {}

func (x *ConfirmTopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTopUpRequest.ProtoReflect.Descriptor instead.
func (*ConfirmTopUpRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmTopUpRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ConfirmTopUpRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ConfirmTopUpRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *ConfirmTopUpRequest) GetWebhookEventId() string {
	if x != nil {
		return x.WebhookEventId
	}
	return ""
}

type ConfirmTopUpResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TopUp         *domain.TopUp             `protobuf:"bytes,1,opt,name=top_up,json=topUp,proto3" json:"top_up,omitempty"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmTopUpResponse) Reset() {
	*x = ConfirmTopUpResponse{}
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmTopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTopUpResponse) ProtoMessage() {}

func (x *ConfirmTopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_balance_admin_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTopUpResponse.ProtoReflect.Descriptor instead.
func (*ConfirmTopUpResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_balance_admin_service_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmTopUpResponse) GetTopUp() *domain.TopUp {
	if x != nil {
		return x.TopUp
	}
	return nil
}

func (x *ConfirmTopUpResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_v1_admin_balance_admin_service_proto protoreflect.FileDescriptor

const file_v1_admin_balance_admin_service_proto_rawDesc = "" +
	"\n" +
	"$v1/admin/balance_admin_service.proto\x129github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin\x1a\x1ev1/domain/balance_domain.proto\"\x99\x01\n" +
	"\x10GetWalletRequest\x12j\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerTypeR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\"o\n" +
	"\x11GetWalletResponse\x12Z\n" +
	"\x06wallet\x18\x01 \x01(\v2B.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletR\x06wallet\"\x8f\x02\n" +
	"\x1cGetWalletTransactionsRequest\x12j\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerTypeR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12(\n" +
	"\rcurrency_code\x18\x03 \x01(\x03H\x00R\fcurrencyCode\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x04R\x06offsetB\x10\n" +
	"\x0e_currency_code\"\x92\x01\n" +
	"\x1dGetWalletTransactionsResponse\x12q\n" +
	"\ftransactions\x18\x01 \x03(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\ftransactions\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\"\x89\x01\n" +
	"\x16GetTransactionResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction\"\xb8\x02\n" +
	"\x15PostAdjustmentRequest\x12j\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerTypeR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x89\x01\n" +
	"\x16PostAdjustmentResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction\"\xf4\x02\n" +
	"\x11ListTopUpsRequest\x12(\n" +
	"\rcurrency_code\x18\x01 \x01(\x03H\x00R\fcurrencyCode\x88\x01\x01\x12r\n" +
	"\rprovider_type\x18\x02 \x01(\x0e2H.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderTypeH\x01R\fproviderType\x88\x01\x01\x12d\n" +
	"\x06status\x18\x03 \x01(\x0e2G.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatusH\x02R\x06status\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x04R\x06offsetB\x10\n" +
	"\x0e_currency_codeB\x10\n" +
	"\x0e_provider_typeB\t\n" +
	"\a_status\"p\n" +
	"\x12ListTopUpsResponse\x12Z\n" +
	"\atop_ups\x18\x01 \x03(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpR\x06topUps\"\xde\x01\n" +
	"\x13ConfirmTopUpRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12(\n" +
	"\x10webhook_event_id\x18\x04 \x01(\tR\x0ewebhookEventId\"\xe1\x01\n" +
	"\x14ConfirmTopUpResponse\x12X\n" +
	"\x06top_up\x18\x01 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpR\x05topUp\x12o\n" +
	"\vtransaction\x18\x02 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction2\xd9\b\n" +
	"\x13BalanceAdminService\x12\xa6\x01\n" +
	"\tGetWallet\x12K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest\x1aL.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse\x12\xca\x01\n" +
	"\x15GetWalletTransactions\x12W.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsRequest\x1aX.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsResponse\x12\xb5\x01\n" +
	"\x0eGetTransaction\x12P.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionRequest\x1aQ.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse\x12\xb5\x01\n" +
	"\x0ePostAdjustment\x12P.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest\x1aQ.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponse\x12\xa9\x01\n" +
	"\n" +
	"ListTopUps\x12L.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsRequest\x1aM.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsResponse\x12\xaf\x01\n" +
	"\fConfirmTopUp\x12N.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpRequest\x1aO.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpResponseBAZ?github.com/martketplace-vkr/balance/pkg/api/grpc/v1/admin;adminb\x06proto3"

var (
	file_v1_admin_balance_admin_service_proto_rawDescOnce sync.Once
	file_v1_admin_balance_admin_service_proto_rawDescData []byte
)

func file_v1_admin_balance_admin_service_proto_rawDescGZIP() []byte {
	file_v1_admin_balance_admin_service_proto_rawDescOnce.Do(func() {
		file_v1_admin_balance_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_balance_admin_service_proto_rawDesc), len(file_v1_admin_balance_admin_service_proto_rawDesc)))
	})
	return file_v1_admin_balance_admin_service_proto_rawDescData
}

var file_v1_admin_balance_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_admin_balance_admin_service_proto_goTypes = []any{
	(*GetWalletRequest)(nil),              // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest
	(*GetWalletResponse)(nil),             // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse
	(*GetWalletTransactionsRequest)(nil),  // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsRequest
	(*GetWalletTransactionsResponse)(nil), // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsResponse
	(*GetTransactionRequest)(nil),         // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionRequest
	(*GetTransactionResponse)(nil),        // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse
	(*PostAdjustmentRequest)(nil),         // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest
	(*PostAdjustmentResponse)(nil),        // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponse
	(*ListTopUpsRequest)(nil),             // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsRequest
	(*ListTopUpsResponse)(nil),            // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsResponse
	(*ConfirmTopUpRequest)(nil),           // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpRequest
	(*ConfirmTopUpResponse)(nil),          // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpResponse
	(domain.WalletOwnerType)(0),           // 12: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	(*domain.Wallet)(nil),                 // 13: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet
	(*domain.LedgerTransaction)(nil),      // 14: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	(*domain.Money)(nil),                  // 15: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	(domain.ProviderType)(0),              // 16: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType
	(domain.TopUpStatus)(0),               // 17: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatus
	(*domain.TopUp)(nil),                  // 18: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
}
var file_v1_admin_balance_admin_service_proto_depIdxs = []int32{
	12, // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest.owner_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	13, // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse.wallet:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet
	12, // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsRequest.owner_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	14, // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsResponse.transactions:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	14, // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	12, // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest.owner_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	15, // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	14, // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	16, // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsRequest.provider_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType
	17, // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsRequest.status:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatus
	18, // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsResponse.top_ups:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
	15, // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	18, // 12: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpResponse.top_up:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
	14, // 13: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	0,  // 14: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetWallet:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletRequest
	2,  // 15: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetWalletTransactions:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsRequest
	4,  // 16: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetTransaction:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionRequest
	6,  // 17: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.PostAdjustment:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentRequest
	8,  // 18: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.ListTopUps:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsRequest
	10, // 19: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.ConfirmTopUp:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpRequest
	1,  // 20: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetWallet:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletResponse
	3,  // 21: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetWalletTransactions:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetWalletTransactionsResponse
	5,  // 22: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.GetTransaction:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.GetTransactionResponse
	7,  // 23: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.PostAdjustment:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.PostAdjustmentResponse
	9,  // 24: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.ListTopUps:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ListTopUpsResponse
	11, // 25: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.BalanceAdminService.ConfirmTopUp:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.admin.ConfirmTopUpResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_admin_balance_admin_service_proto_init() }
func file_v1_admin_balance_admin_service_proto_init() {
	if File_v1_admin_balance_admin_service_proto != nil {
		return
	}
	file_v1_admin_balance_admin_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1_admin_balance_admin_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_balance_admin_service_proto_rawDesc), len(file_v1_admin_balance_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_balance_admin_service_proto_goTypes,
		DependencyIndexes: file_v1_admin_balance_admin_service_proto_depIdxs,
		MessageInfos:      file_v1_admin_balance_admin_service_proto_msgTypes,
	}.Build()
	File_v1_admin_balance_admin_service_proto = out.File
	file_v1_admin_balance_admin_service_proto_goTypes = nil
	file_v1_admin_balance_admin_service_proto_depIdxs = nil
}
