// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: v1/domain/balance_domain.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletOwnerType int32

const (
	WalletOwnerType_WALLET_OWNER_TYPE_UNSPECIFIED WalletOwnerType = 0
	WalletOwnerType_WALLET_OWNER_TYPE_USER        WalletOwnerType = 1
	WalletOwnerType_WALLET_OWNER_TYPE_VENDOR      WalletOwnerType = 2
	WalletOwnerType_WALLET_OWNER_TYPE_SYSTEM      WalletOwnerType = 3
)

// Enum value maps for WalletOwnerType.
var (
	WalletOwnerType_name = map[int32]string{
		0: "WALLET_OWNER_TYPE_UNSPECIFIED",
		1: "WALLET_OWNER_TYPE_USER",
		2: "WALLET_OWNER_TYPE_VENDOR",
		3: "WALLET_OWNER_TYPE_SYSTEM",
	}
	WalletOwnerType_value = map[string]int32{
		"WALLET_OWNER_TYPE_UNSPECIFIED": 0,
		"WALLET_OWNER_TYPE_USER":        1,
		"WALLET_OWNER_TYPE_VENDOR":      2,
		"WALLET_OWNER_TYPE_SYSTEM":      3,
	}
)

func (x WalletOwnerType) Enum() *WalletOwnerType {
	p := new(WalletOwnerType)
	*p = x
	return p
}

func (x WalletOwnerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletOwnerType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[0].Descriptor()
}

func (WalletOwnerType) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[0]
}

func (x WalletOwnerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletOwnerType.Descriptor instead.
func (WalletOwnerType) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{0}
}

type WalletStatus int32

const (
	WalletStatus_WALLET_STATUS_UNSPECIFIED WalletStatus = 0
	WalletStatus_WALLET_STATUS_ACTIVE      WalletStatus = 1
	WalletStatus_WALLET_STATUS_FROZEN      WalletStatus = 2
	WalletStatus_WALLET_STATUS_CLOSED      WalletStatus = 3
)

// Enum value maps for WalletStatus.
var (
	WalletStatus_name = map[int32]string{
		0: "WALLET_STATUS_UNSPECIFIED",
		1: "WALLET_STATUS_ACTIVE",
		2: "WALLET_STATUS_FROZEN",
		3: "WALLET_STATUS_CLOSED",
	}
	WalletStatus_value = map[string]int32{
		"WALLET_STATUS_UNSPECIFIED": 0,
		"WALLET_STATUS_ACTIVE":      1,
		"WALLET_STATUS_FROZEN":      2,
		"WALLET_STATUS_CLOSED":      3,
	}
)

func (x WalletStatus) Enum() *WalletStatus {
	p := new(WalletStatus)
	*p = x
	return p
}

func (x WalletStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[1].Descriptor()
}

func (WalletStatus) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[1]
}

func (x WalletStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletStatus.Descriptor instead.
func (WalletStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{1}
}

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_AVAILABLE   AccountType = 1
	AccountType_ACCOUNT_TYPE_HOLD        AccountType = 2
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_AVAILABLE",
		2: "ACCOUNT_TYPE_HOLD",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_AVAILABLE":   1,
		"ACCOUNT_TYPE_HOLD":        2,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[2].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[2]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{2}
}

type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ACTIVE      AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_FROZEN      AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_CLOSED      AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_FROZEN",
		3: "ACCOUNT_STATUS_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_ACTIVE":      1,
		"ACCOUNT_STATUS_FROZEN":      2,
		"ACCOUNT_STATUS_CLOSED":      3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[3].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[3]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{3}
}

type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	ProviderType_PROVIDER_TYPE_ACQUIRING   ProviderType = 1
	ProviderType_PROVIDER_TYPE_CRYPTO      ProviderType = 2
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_ACQUIRING",
		2: "PROVIDER_TYPE_CRYPTO",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_ACQUIRING":   1,
		"PROVIDER_TYPE_CRYPTO":      2,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[4].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[4]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{4}
}

type TopUpStatus int32

const (
	TopUpStatus_TOP_UP_STATUS_UNSPECIFIED TopUpStatus = 0
	TopUpStatus_TOP_UP_STATUS_CREATED     TopUpStatus = 1
	TopUpStatus_TOP_UP_STATUS_PENDING     TopUpStatus = 2
	TopUpStatus_TOP_UP_STATUS_PAID        TopUpStatus = 3
	TopUpStatus_TOP_UP_STATUS_CONFIRMED   TopUpStatus = 4
	TopUpStatus_TOP_UP_STATUS_FAILED      TopUpStatus = 5
	TopUpStatus_TOP_UP_STATUS_CANCELED    TopUpStatus = 6
	TopUpStatus_TOP_UP_STATUS_EXPIRED     TopUpStatus = 7
)

// Enum value maps for TopUpStatus.
var (
	TopUpStatus_name = map[int32]string{
		0: "TOP_UP_STATUS_UNSPECIFIED",
		1: "TOP_UP_STATUS_CREATED",
		2: "TOP_UP_STATUS_PENDING",
		3: "TOP_UP_STATUS_PAID",
		4: "TOP_UP_STATUS_CONFIRMED",
		5: "TOP_UP_STATUS_FAILED",
		6: "TOP_UP_STATUS_CANCELED",
		7: "TOP_UP_STATUS_EXPIRED",
	}
	TopUpStatus_value = map[string]int32{
		"TOP_UP_STATUS_UNSPECIFIED": 0,
		"TOP_UP_STATUS_CREATED":     1,
		"TOP_UP_STATUS_PENDING":     2,
		"TOP_UP_STATUS_PAID":        3,
		"TOP_UP_STATUS_CONFIRMED":   4,
		"TOP_UP_STATUS_FAILED":      5,
		"TOP_UP_STATUS_CANCELED":    6,
		"TOP_UP_STATUS_EXPIRED":     7,
	}
)

func (x TopUpStatus) Enum() *TopUpStatus {
	p := new(TopUpStatus)
	*p = x
	return p
}

func (x TopUpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopUpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[5].Descriptor()
}

func (TopUpStatus) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[5]
}

func (x TopUpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopUpStatus.Descriptor instead.
func (TopUpStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{5}
}

type WithdrawalStatus int32

const (
	WithdrawalStatus_WITHDRAWAL_STATUS_UNSPECIFIED WithdrawalStatus = 0
	WithdrawalStatus_WITHDRAWAL_STATUS_CREATED     WithdrawalStatus = 1
	WithdrawalStatus_WITHDRAWAL_STATUS_PENDING     WithdrawalStatus = 2
	WithdrawalStatus_WITHDRAWAL_STATUS_COMPLETED   WithdrawalStatus = 3
	WithdrawalStatus_WITHDRAWAL_STATUS_FAILED      WithdrawalStatus = 4
	WithdrawalStatus_WITHDRAWAL_STATUS_CANCELED    WithdrawalStatus = 5
)

// Enum value maps for WithdrawalStatus.
var (
	WithdrawalStatus_name = map[int32]string{
		0: "WITHDRAWAL_STATUS_UNSPECIFIED",
		1: "WITHDRAWAL_STATUS_CREATED",
		2: "WITHDRAWAL_STATUS_PENDING",
		3: "WITHDRAWAL_STATUS_COMPLETED",
		4: "WITHDRAWAL_STATUS_FAILED",
		5: "WITHDRAWAL_STATUS_CANCELED",
	}
	WithdrawalStatus_value = map[string]int32{
		"WITHDRAWAL_STATUS_UNSPECIFIED": 0,
		"WITHDRAWAL_STATUS_CREATED":     1,
		"WITHDRAWAL_STATUS_PENDING":     2,
		"WITHDRAWAL_STATUS_COMPLETED":   3,
		"WITHDRAWAL_STATUS_FAILED":      4,
		"WITHDRAWAL_STATUS_CANCELED":    5,
	}
)

func (x WithdrawalStatus) Enum() *WithdrawalStatus {
	p := new(WithdrawalStatus)
	*p = x
	return p
}

func (x WithdrawalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WithdrawalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[6].Descriptor()
}

func (WithdrawalStatus) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[6]
}

func (x WithdrawalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WithdrawalStatus.Descriptor instead.
func (WithdrawalStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{6}
}

type LedgerTransactionType int32

const (
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_UNSPECIFIED LedgerTransactionType = 0
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_TOP_UP      LedgerTransactionType = 1
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_HOLD        LedgerTransactionType = 2
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_CAPTURE     LedgerTransactionType = 3
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_RELEASE     LedgerTransactionType = 4
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_REFUND      LedgerTransactionType = 5
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_WITHDRAWAL  LedgerTransactionType = 6
	LedgerTransactionType_LEDGER_TRANSACTION_TYPE_ADJUSTMENT  LedgerTransactionType = 7
)

// Enum value maps for LedgerTransactionType.
var (
	LedgerTransactionType_name = map[int32]string{
		0: "LEDGER_TRANSACTION_TYPE_UNSPECIFIED",
		1: "LEDGER_TRANSACTION_TYPE_TOP_UP",
		2: "LEDGER_TRANSACTION_TYPE_HOLD",
		3: "LEDGER_TRANSACTION_TYPE_CAPTURE",
		4: "LEDGER_TRANSACTION_TYPE_RELEASE",
		5: "LEDGER_TRANSACTION_TYPE_REFUND",
		6: "LEDGER_TRANSACTION_TYPE_WITHDRAWAL",
		7: "LEDGER_TRANSACTION_TYPE_ADJUSTMENT",
	}
	LedgerTransactionType_value = map[string]int32{
		"LEDGER_TRANSACTION_TYPE_UNSPECIFIED": 0,
		"LEDGER_TRANSACTION_TYPE_TOP_UP":      1,
		"LEDGER_TRANSACTION_TYPE_HOLD":        2,
		"LEDGER_TRANSACTION_TYPE_CAPTURE":     3,
		"LEDGER_TRANSACTION_TYPE_RELEASE":     4,
		"LEDGER_TRANSACTION_TYPE_REFUND":      5,
		"LEDGER_TRANSACTION_TYPE_WITHDRAWAL":  6,
		"LEDGER_TRANSACTION_TYPE_ADJUSTMENT":  7,
	}
)

func (x LedgerTransactionType) Enum() *LedgerTransactionType {
	p := new(LedgerTransactionType)
	*p = x
	return p
}

func (x LedgerTransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerTransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[7].Descriptor()
}

func (LedgerTransactionType) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[7]
}

func (x LedgerTransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerTransactionType.Descriptor instead.
func (LedgerTransactionType) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{7}
}

type LedgerTransactionStatus int32

const (
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_UNSPECIFIED LedgerTransactionStatus = 0
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_PENDING     LedgerTransactionStatus = 1
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_POSTED      LedgerTransactionStatus = 2
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_REVERSED    LedgerTransactionStatus = 3
	LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_FAILED      LedgerTransactionStatus = 4
)

// Enum value maps for LedgerTransactionStatus.
var (
	LedgerTransactionStatus_name = map[int32]string{
		0: "LEDGER_TRANSACTION_STATUS_UNSPECIFIED",
		1: "LEDGER_TRANSACTION_STATUS_PENDING",
		2: "LEDGER_TRANSACTION_STATUS_POSTED",
		3: "LEDGER_TRANSACTION_STATUS_REVERSED",
		4: "LEDGER_TRANSACTION_STATUS_FAILED",
	}
	LedgerTransactionStatus_value = map[string]int32{
		"LEDGER_TRANSACTION_STATUS_UNSPECIFIED": 0,
		"LEDGER_TRANSACTION_STATUS_PENDING":     1,
		"LEDGER_TRANSACTION_STATUS_POSTED":      2,
		"LEDGER_TRANSACTION_STATUS_REVERSED":    3,
		"LEDGER_TRANSACTION_STATUS_FAILED":      4,
	}
)

func (x LedgerTransactionStatus) Enum() *LedgerTransactionStatus {
	p := new(LedgerTransactionStatus)
	*p = x
	return p
}

func (x LedgerTransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LedgerTransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[8].Descriptor()
}

func (LedgerTransactionStatus) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[8]
}

func (x LedgerTransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LedgerTransactionStatus.Descriptor instead.
func (LedgerTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{8}
}

type EntryDirection int32

const (
	EntryDirection_ENTRY_DIRECTION_UNSPECIFIED EntryDirection = 0
	EntryDirection_ENTRY_DIRECTION_DEBIT       EntryDirection = 1
	EntryDirection_ENTRY_DIRECTION_CREDIT      EntryDirection = 2
)

// Enum value maps for EntryDirection.
var (
	EntryDirection_name = map[int32]string{
		0: "ENTRY_DIRECTION_UNSPECIFIED",
		1: "ENTRY_DIRECTION_DEBIT",
		2: "ENTRY_DIRECTION_CREDIT",
	}
	EntryDirection_value = map[string]int32{
		"ENTRY_DIRECTION_UNSPECIFIED": 0,
		"ENTRY_DIRECTION_DEBIT":       1,
		"ENTRY_DIRECTION_CREDIT":      2,
	}
)

func (x EntryDirection) Enum() *EntryDirection {
	p := new(EntryDirection)
	*p = x
	return p
}

func (x EntryDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[9].Descriptor()
}

func (EntryDirection) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[9]
}

func (x EntryDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryDirection.Descriptor instead.
func (EntryDirection) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{9}
}

type ReferenceType int32

const (
	ReferenceType_REFERENCE_TYPE_UNSPECIFIED      ReferenceType = 0
	ReferenceType_REFERENCE_TYPE_TOP_UP           ReferenceType = 1
	ReferenceType_REFERENCE_TYPE_ORDER            ReferenceType = 2
	ReferenceType_REFERENCE_TYPE_WITHDRAWAL       ReferenceType = 3
	ReferenceType_REFERENCE_TYPE_MANUAL_OPERATION ReferenceType = 4
)

// Enum value maps for ReferenceType.
var (
	ReferenceType_name = map[int32]string{
		0: "REFERENCE_TYPE_UNSPECIFIED",
		1: "REFERENCE_TYPE_TOP_UP",
		2: "REFERENCE_TYPE_ORDER",
		3: "REFERENCE_TYPE_WITHDRAWAL",
		4: "REFERENCE_TYPE_MANUAL_OPERATION",
	}
	ReferenceType_value = map[string]int32{
		"REFERENCE_TYPE_UNSPECIFIED":      0,
		"REFERENCE_TYPE_TOP_UP":           1,
		"REFERENCE_TYPE_ORDER":            2,
		"REFERENCE_TYPE_WITHDRAWAL":       3,
		"REFERENCE_TYPE_MANUAL_OPERATION": 4,
	}
)

func (x ReferenceType) Enum() *ReferenceType {
	p := new(ReferenceType)
	*p = x
	return p
}

func (x ReferenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[10].Descriptor()
}

func (ReferenceType) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[10]
}

func (x ReferenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferenceType.Descriptor instead.
func (ReferenceType) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{10}
}

type DestinationType int32

const (
	DestinationType_DESTINATION_TYPE_UNSPECIFIED   DestinationType = 0
	DestinationType_DESTINATION_TYPE_BANK_CARD     DestinationType = 1
	DestinationType_DESTINATION_TYPE_CRYPTO_WALLET DestinationType = 2
	DestinationType_DESTINATION_TYPE_BANK_ACCOUNT  DestinationType = 3
)

// Enum value maps for DestinationType.
var (
	DestinationType_name = map[int32]string{
		0: "DESTINATION_TYPE_UNSPECIFIED",
		1: "DESTINATION_TYPE_BANK_CARD",
		2: "DESTINATION_TYPE_CRYPTO_WALLET",
		3: "DESTINATION_TYPE_BANK_ACCOUNT",
	}
	DestinationType_value = map[string]int32{
		"DESTINATION_TYPE_UNSPECIFIED":   0,
		"DESTINATION_TYPE_BANK_CARD":     1,
		"DESTINATION_TYPE_CRYPTO_WALLET": 2,
		"DESTINATION_TYPE_BANK_ACCOUNT":  3,
	}
)

func (x DestinationType) Enum() *DestinationType {
	p := new(DestinationType)
	*p = x
	return p
}

func (x DestinationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestinationType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_domain_balance_domain_proto_enumTypes[11].Descriptor()
}

func (DestinationType) Type() protoreflect.EnumType {
	return &file_v1_domain_balance_domain_proto_enumTypes[11]
}

func (x DestinationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestinationType.Descriptor instead.
func (DestinationType) EnumDescriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{11}
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyCode  int64                  `protobuf:"varint,2,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Money) GetCurrencyCode() int64 {
	if x != nil {
		return x.CurrencyCode
	}
	return 0
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerType     WalletOwnerType        `protobuf:"varint,2,opt,name=owner_type,json=ownerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType" json:"owner_type,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status        WalletStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletStatus" json:"status,omitempty"`
	Accounts      []*Account             `protobuf:"bytes,5,rep,name=accounts,proto3" json:"accounts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{1}
}

func (x *Wallet) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wallet) GetOwnerType() WalletOwnerType {
	if x != nil {
		return x.OwnerType
	}
	return WalletOwnerType_WALLET_OWNER_TYPE_UNSPECIFIED
}

func (x *Wallet) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Wallet) GetStatus() WalletStatus {
	if x != nil {
		return x.Status
	}
	return WalletStatus_WALLET_STATUS_UNSPECIFIED
}

func (x *Wallet) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wallet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId      int64                  `protobuf:"varint,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	CurrencyCode  int64                  `protobuf:"varint,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	AccountType   AccountType            `protobuf:"varint,4,opt,name=account_type,json=accountType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountType" json:"account_type,omitempty"`
	Status        AccountStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountStatus" json:"status,omitempty"`
	Balance       string                 `protobuf:"bytes,6,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *Account) GetCurrencyCode() int64 {
	if x != nil {
		return x.CurrencyCode
	}
	return 0
}

func (x *Account) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DepositAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositAddress) Reset() {
	*x = DepositAddress{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAddress) ProtoMessage() {}

func (x *DepositAddress) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAddress.ProtoReflect.Descriptor instead.
func (*DepositAddress) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{3}
}

func (x *DepositAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepositAddress) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DepositAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DepositAddress) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DepositAddress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DepositAddress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Direction     EntryDirection         `protobuf:"varint,3,opt,name=direction,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.EntryDirection" json:"direction,omitempty"`
	Money         *Money                 `protobuf:"bytes,4,opt,name=money,proto3" json:"money,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{4}
}

func (x *LedgerEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerEntry) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LedgerEntry) GetDirection() EntryDirection {
	if x != nil {
		return x.Direction
	}
	return EntryDirection_ENTRY_DIRECTION_UNSPECIFIED
}

func (x *LedgerEntry) GetMoney() *Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *LedgerEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LedgerTransaction struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey string                  `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Type           LedgerTransactionType   `protobuf:"varint,3,opt,name=type,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionType" json:"type,omitempty"`
	Status         LedgerTransactionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionStatus" json:"status,omitempty"`
	Reason         string                  `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ReferenceType  ReferenceType           `protobuf:"varint,6,opt,name=reference_type,json=referenceType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ReferenceType" json:"reference_type,omitempty"`
	ReferenceId    string                  `protobuf:"bytes,7,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Entries        []*LedgerEntry          `protobuf:"bytes,8,rep,name=entries,proto3" json:"entries,omitempty"`
	CreatedAt      *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PostedAt       *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	ReversedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=reversed_at,json=reversedAt,proto3" json:"reversed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LedgerTransaction) Reset() {
	*x = LedgerTransaction{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerTransaction) ProtoMessage() {}

func (x *LedgerTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerTransaction.ProtoReflect.Descriptor instead.
func (*LedgerTransaction) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{5}
}

func (x *LedgerTransaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerTransaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LedgerTransaction) GetType() LedgerTransactionType {
	if x != nil {
		return x.Type
	}
	return LedgerTransactionType_LEDGER_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *LedgerTransaction) GetStatus() LedgerTransactionStatus {
	if x != nil {
		return x.Status
	}
	return LedgerTransactionStatus_LEDGER_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *LedgerTransaction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LedgerTransaction) GetReferenceType() ReferenceType {
	if x != nil {
		return x.ReferenceType
	}
	return ReferenceType_REFERENCE_TYPE_UNSPECIFIED
}

func (x *LedgerTransaction) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *LedgerTransaction) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LedgerTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LedgerTransaction) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *LedgerTransaction) GetReversedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReversedAt
	}
	return nil
}

type TopUp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId       int64                  `protobuf:"varint,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Money          *Money                 `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	ProviderType   ProviderType           `protobuf:"varint,4,opt,name=provider_type,json=providerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType" json:"provider_type,omitempty"`
	ProviderName   string                 `protobuf:"bytes,5,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Status         TopUpStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatus" json:"status,omitempty"`
	ExternalId     string                 `protobuf:"bytes,7,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ExternalStatus string                 `protobuf:"bytes,8,opt,name=external_status,json=externalStatus,proto3" json:"external_status,omitempty"`
	PaymentUrl     string                 `protobuf:"bytes,9,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	WalletAddress  string                 `protobuf:"bytes,10,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	WalletTag      string                 `protobuf:"bytes,11,opt,name=wallet_tag,json=walletTag,proto3" json:"wallet_tag,omitempty"`
	Network        string                 `protobuf:"bytes,12,opt,name=network,proto3" json:"network,omitempty"`
	TxHash         string                 `protobuf:"bytes,13,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,14,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ConfirmedAt    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopUp) Reset() {
	*x = TopUp{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUp) ProtoMessage() {}

func (x *TopUp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUp.ProtoReflect.Descriptor instead.
func (*TopUp) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{6}
}

func (x *TopUp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopUp) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *TopUp) GetMoney() *Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *TopUp) GetProviderType() ProviderType {
	if x != nil {
		return x.ProviderType
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *TopUp) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *TopUp) GetStatus() TopUpStatus {
	if x != nil {
		return x.Status
	}
	return TopUpStatus_TOP_UP_STATUS_UNSPECIFIED
}

func (x *TopUp) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *TopUp) GetExternalStatus() string {
	if x != nil {
		return x.ExternalStatus
	}
	return ""
}

func (x *TopUp) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *TopUp) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *TopUp) GetWalletTag() string {
	if x != nil {
		return x.WalletTag
	}
	return ""
}

func (x *TopUp) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TopUp) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TopUp) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TopUp) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TopUp) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *TopUp) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *TopUp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TopUp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Withdrawal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId        int64                  `protobuf:"varint,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Money           *Money                 `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	DestinationType DestinationType        `protobuf:"varint,4,opt,name=destination_type,json=destinationType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationType" json:"destination_type,omitempty"`
	Destination     string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	Status          WithdrawalStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WithdrawalStatus" json:"status,omitempty"`
	ExternalId      string                 `protobuf:"bytes,7,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	RequestedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	ProcessedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_v1_domain_balance_domain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_v1_domain_balance_domain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_v1_domain_balance_domain_proto_rawDescGZIP(), []int{7}
}

func (x *Withdrawal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Withdrawal) GetWalletId() int64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *Withdrawal) GetMoney() *Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *Withdrawal) GetDestinationType() DestinationType {
	if x != nil {
		return x.DestinationType
	}
	return DestinationType_DESTINATION_TYPE_UNSPECIFIED
}

func (x *Withdrawal) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Withdrawal) GetStatus() WithdrawalStatus {
	if x != nil {
		return x.Status
	}
	return WithdrawalStatus_WITHDRAWAL_STATUS_UNSPECIFIED
}

func (x *Withdrawal) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Withdrawal) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Withdrawal) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

func (x *Withdrawal) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *Withdrawal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Withdrawal) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_v1_domain_balance_domain_proto protoreflect.FileDescriptor

const file_v1_domain_balance_domain_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/domain/balance_domain.proto\x12:github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12#\n" +
	"\rcurrency_code\x18\x02 \x01(\x03R\fcurrencyCode\"\xd8\x03\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12j\n" +
	"\n" +
	"owner_type\x18\x02 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerTypeR\townerType\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12`\n" +
	"\x06status\x18\x04 \x01(\x0e2H.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletStatusR\x06status\x12_\n" +
	"\baccounts\x18\x05 \x03(\v2C.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountR\baccounts\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xba\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\x03R\bwalletId\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\x03R\fcurrencyCode\x12j\n" +
	"\faccount_type\x18\x04 \x01(\x0e2G.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountTypeR\vaccountType\x12a\n" +
	"\x06status\x18\x05 \x01(\x0e2I.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountStatusR\x06status\x12\x18\n" +
	"\abalance\x18\x06 \x01(\tR\abalance\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe3\x01\n" +
	"\x0eDepositAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xba\x02\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12h\n" +
	"\tdirection\x18\x03 \x01(\x0e2J.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.EntryDirectionR\tdirection\x12W\n" +
	"\x05money\x18\x04 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe1\x05\n" +
	"\x11LedgerTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12e\n" +
	"\x04type\x18\x03 \x01(\x0e2Q.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionTypeR\x04type\x12k\n" +
	"\x06status\x18\x04 \x01(\x0e2S.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12p\n" +
	"\x0ereference_type\x18\x06 \x01(\x0e2I.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ReferenceTypeR\rreferenceType\x12!\n" +
	"\freference_id\x18\a \x01(\tR\vreferenceId\x12a\n" +
	"\aentries\x18\b \x03(\v2G.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerEntryR\aentries\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tposted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x12;\n" +
	"\vreversed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reversedAt\"\xb4\a\n" +
	"\x05TopUp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\x03R\bwalletId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12m\n" +
	"\rprovider_type\x18\x04 \x01(\x0e2H.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderTypeR\fproviderType\x12#\n" +
	"\rprovider_name\x18\x05 \x01(\tR\fproviderName\x12_\n" +
	"\x06status\x18\x06 \x01(\x0e2G.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatusR\x06status\x12\x1f\n" +
	"\vexternal_id\x18\a \x01(\tR\n" +
	"externalId\x12'\n" +
	"\x0fexternal_status\x18\b \x01(\tR\x0eexternalStatus\x12\x1f\n" +
	"\vpayment_url\x18\t \x01(\tR\n" +
	"paymentUrl\x12%\n" +
	"\x0ewallet_address\x18\n" +
	" \x01(\tR\rwalletAddress\x12\x1d\n" +
	"\n" +
	"wallet_tag\x18\v \x01(\tR\twalletTag\x12\x18\n" +
	"\anetwork\x18\f \x01(\tR\anetwork\x12\x17\n" +
	"\atx_hash\x18\r \x01(\tR\x06txHash\x12'\n" +
	"\x0fidempotency_key\x18\x0e \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"expires_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x123\n" +
	"\apaid_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x12=\n" +
	"\fconfirmed_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd0\x05\n" +
	"\n" +
	"Withdrawal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\x03R\bwalletId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12v\n" +
	"\x10destination_type\x18\x04 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationTypeR\x0fdestinationType\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\x12d\n" +
	"\x06status\x18\x06 \x01(\x0e2L.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WithdrawalStatusR\x06status\x12\x1f\n" +
	"\vexternal_id\x18\a \x01(\tR\n" +
	"externalId\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12=\n" +
	"\frequested_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\x12=\n" +
	"\fprocessed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x8c\x01\n" +
	"\x0fWalletOwnerType\x12!\n" +
	"\x1dWALLET_OWNER_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WALLET_OWNER_TYPE_USER\x10\x01\x12\x1c\n" +
	"\x18WALLET_OWNER_TYPE_VENDOR\x10\x02\x12\x1c\n" +
	"\x18WALLET_OWNER_TYPE_SYSTEM\x10\x03*{\n" +
	"\fWalletStatus\x12\x1d\n" +
	"\x19WALLET_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14WALLET_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14WALLET_STATUS_FROZEN\x10\x02\x12\x18\n" +
	"\x14WALLET_STATUS_CLOSED\x10\x03*^\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_AVAILABLE\x10\x01\x12\x15\n" +
	"\x11ACCOUNT_TYPE_HOLD\x10\x02*\x80\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_FROZEN\x10\x02\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x03*d\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROVIDER_TYPE_ACQUIRING\x10\x01\x12\x18\n" +
	"\x14PROVIDER_TYPE_CRYPTO\x10\x02*\xe8\x01\n" +
	"\vTopUpStatus\x12\x1d\n" +
	"\x19TOP_UP_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TOP_UP_STATUS_CREATED\x10\x01\x12\x19\n" +
	"\x15TOP_UP_STATUS_PENDING\x10\x02\x12\x16\n" +
	"\x12TOP_UP_STATUS_PAID\x10\x03\x12\x1b\n" +
	"\x17TOP_UP_STATUS_CONFIRMED\x10\x04\x12\x18\n" +
	"\x14TOP_UP_STATUS_FAILED\x10\x05\x12\x1a\n" +
	"\x16TOP_UP_STATUS_CANCELED\x10\x06\x12\x19\n" +
	"\x15TOP_UP_STATUS_EXPIRED\x10\a*\xd2\x01\n" +
	"\x10WithdrawalStatus\x12!\n" +
	"\x1dWITHDRAWAL_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WITHDRAWAL_STATUS_CREATED\x10\x01\x12\x1d\n" +
	"\x19WITHDRAWAL_STATUS_PENDING\x10\x02\x12\x1f\n" +
	"\x1bWITHDRAWAL_STATUS_COMPLETED\x10\x03\x12\x1c\n" +
	"\x18WITHDRAWAL_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aWITHDRAWAL_STATUS_CANCELED\x10\x05*\xc4\x02\n" +
	"\x15LedgerTransactionType\x12'\n" +
	"#LEDGER_TRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eLEDGER_TRANSACTION_TYPE_TOP_UP\x10\x01\x12 \n" +
	"\x1cLEDGER_TRANSACTION_TYPE_HOLD\x10\x02\x12#\n" +
	"\x1fLEDGER_TRANSACTION_TYPE_CAPTURE\x10\x03\x12#\n" +
	"\x1fLEDGER_TRANSACTION_TYPE_RELEASE\x10\x04\x12\"\n" +
	"\x1eLEDGER_TRANSACTION_TYPE_REFUND\x10\x05\x12&\n" +
	"\"LEDGER_TRANSACTION_TYPE_WITHDRAWAL\x10\x06\x12&\n" +
	"\"LEDGER_TRANSACTION_TYPE_ADJUSTMENT\x10\a*\xdf\x01\n" +
	"\x17LedgerTransactionStatus\x12)\n" +
	"%LEDGER_TRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!LEDGER_TRANSACTION_STATUS_PENDING\x10\x01\x12$\n" +
	" LEDGER_TRANSACTION_STATUS_POSTED\x10\x02\x12&\n" +
	"\"LEDGER_TRANSACTION_STATUS_REVERSED\x10\x03\x12$\n" +
	" LEDGER_TRANSACTION_STATUS_FAILED\x10\x04*h\n" +
	"\x0eEntryDirection\x12\x1f\n" +
	"\x1bENTRY_DIRECTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENTRY_DIRECTION_DEBIT\x10\x01\x12\x1a\n" +
	"\x16ENTRY_DIRECTION_CREDIT\x10\x02*\xa8\x01\n" +
	"\rReferenceType\x12\x1e\n" +
	"\x1aREFERENCE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REFERENCE_TYPE_TOP_UP\x10\x01\x12\x18\n" +
	"\x14REFERENCE_TYPE_ORDER\x10\x02\x12\x1d\n" +
	"\x19REFERENCE_TYPE_WITHDRAWAL\x10\x03\x12#\n" +
	"\x1fREFERENCE_TYPE_MANUAL_OPERATION\x10\x04*\x9a\x01\n" +
	"\x0fDestinationType\x12 \n" +
	"\x1cDESTINATION_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDESTINATION_TYPE_BANK_CARD\x10\x01\x12\"\n" +
	"\x1eDESTINATION_TYPE_CRYPTO_WALLET\x10\x02\x12!\n" +
	"\x1dDESTINATION_TYPE_BANK_ACCOUNT\x10\x03BCZAgithub.com/martketplace-vkr/balance/pkg/api/grpc/v1/domain;domainb\x06proto3"

var (
	file_v1_domain_balance_domain_proto_rawDescOnce sync.Once
	file_v1_domain_balance_domain_proto_rawDescData []byte
)

func file_v1_domain_balance_domain_proto_rawDescGZIP() []byte {
	file_v1_domain_balance_domain_proto_rawDescOnce.Do(func() {
		file_v1_domain_balance_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_domain_balance_domain_proto_rawDesc), len(file_v1_domain_balance_domain_proto_rawDesc)))
	})
	return file_v1_domain_balance_domain_proto_rawDescData
}

var file_v1_domain_balance_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_v1_domain_balance_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_domain_balance_domain_proto_goTypes = []any{
	(WalletOwnerType)(0),          // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	(WalletStatus)(0),             // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletStatus
	(AccountType)(0),              // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountType
	(AccountStatus)(0),            // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountStatus
	(ProviderType)(0),             // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType
	(TopUpStatus)(0),              // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatus
	(WithdrawalStatus)(0),         // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WithdrawalStatus
	(LedgerTransactionType)(0),    // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionType
	(LedgerTransactionStatus)(0),  // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionStatus
	(EntryDirection)(0),           // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.EntryDirection
	(ReferenceType)(0),            // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ReferenceType
	(DestinationType)(0),          // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationType
	(*Money)(nil),                 // 12: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	(*Wallet)(nil),                // 13: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet
	(*Account)(nil),               // 14: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Account
	(*DepositAddress)(nil),        // 15: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DepositAddress
	(*LedgerEntry)(nil),           // 16: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerEntry
	(*LedgerTransaction)(nil),     // 17: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	(*TopUp)(nil),                 // 18: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
	(*Withdrawal)(nil),            // 19: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_v1_domain_balance_domain_proto_depIdxs = []int32{
	0,  // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet.owner_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletOwnerType
	1,  // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet.status:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletStatus
	14, // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet.accounts:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Account
	20, // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Account.account_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountType
	3,  // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Account.status:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.AccountStatus
	20, // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Account.created_at:type_name -> google.protobuf.Timestamp
	20, // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Account.updated_at:type_name -> google.protobuf.Timestamp
	20, // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DepositAddress.created_at:type_name -> google.protobuf.Timestamp
	20, // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DepositAddress.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerEntry.direction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.EntryDirection
	12, // 12: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerEntry.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	20, // 13: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerEntry.created_at:type_name -> google.protobuf.Timestamp
	7,  // 14: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction.type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionType
	8,  // 15: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction.status:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionStatus
	10, // 16: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction.reference_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ReferenceType
	16, // 17: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction.entries:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerEntry
	20, // 18: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction.created_at:type_name -> google.protobuf.Timestamp
	20, // 19: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction.posted_at:type_name -> google.protobuf.Timestamp
	20, // 20: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction.reversed_at:type_name -> google.protobuf.Timestamp
	12, // 21: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	4,  // 22: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.provider_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType
	5,  // 23: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.status:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpStatus
	20, // 24: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.expires_at:type_name -> google.protobuf.Timestamp
	20, // 25: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.paid_at:type_name -> google.protobuf.Timestamp
	20, // 26: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.confirmed_at:type_name -> google.protobuf.Timestamp
	20, // 27: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.created_at:type_name -> google.protobuf.Timestamp
	20, // 28: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp.updated_at:type_name -> google.protobuf.Timestamp
	12, // 29: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	11, // 30: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal.destination_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationType
	6,  // 31: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal.status:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WithdrawalStatus
	20, // 32: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal.requested_at:type_name -> google.protobuf.Timestamp
	20, // 33: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal.processed_at:type_name -> google.protobuf.Timestamp
	20, // 34: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal.created_at:type_name -> google.protobuf.Timestamp
	20, // 35: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal.updated_at:type_name -> google.protobuf.Timestamp
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_v1_domain_balance_domain_proto_init() }
func file_v1_domain_balance_domain_proto_init() {
	if File_v1_domain_balance_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_domain_balance_domain_proto_rawDesc), len(file_v1_domain_balance_domain_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_domain_balance_domain_proto_goTypes,
		DependencyIndexes: file_v1_domain_balance_domain_proto_depIdxs,
		EnumInfos:         file_v1_domain_balance_domain_proto_enumTypes,
		MessageInfos:      file_v1_domain_balance_domain_proto_msgTypes,
	}.Build()
	File_v1_domain_balance_domain_proto = out.File
	file_v1_domain_balance_domain_proto_goTypes = nil
	file_v1_domain_balance_domain_proto_depIdxs = nil
}
