// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.5
// source: v1/order/balance_order_service.proto

package order

import (
	domain "github.com/martketplace-vkr/balance/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveFundsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveFundsRequest) Reset() {
	*x = ReserveFundsRequest{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveFundsRequest) ProtoMessage() {}

func (x *ReserveFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveFundsRequest.ProtoReflect.Descriptor instead.
func (*ReserveFundsRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveFundsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveFundsRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveFundsRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *ReserveFundsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReserveFundsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReserveFundsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveFundsResponse) Reset() {
	*x = ReserveFundsResponse{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveFundsResponse) ProtoMessage() {}

func (x *ReserveFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveFundsResponse.ProtoReflect.Descriptor instead.
func (*ReserveFundsResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveFundsResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type CaptureFundsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptureFundsRequest) Reset() {
	*x = CaptureFundsRequest{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureFundsRequest) ProtoMessage() {}

func (x *CaptureFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureFundsRequest.ProtoReflect.Descriptor instead.
func (*CaptureFundsRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureFundsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CaptureFundsRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CaptureFundsRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *CaptureFundsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CaptureFundsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CaptureFundsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureFundsResponse) Reset() {
	*x = CaptureFundsResponse{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureFundsResponse) ProtoMessage() {}

func (x *CaptureFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureFundsResponse.ProtoReflect.Descriptor instead.
func (*CaptureFundsResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureFundsResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ReleaseFundsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseFundsRequest) Reset() {
	*x = ReleaseFundsRequest{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseFundsRequest) ProtoMessage() {}

func (x *ReleaseFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseFundsRequest.ProtoReflect.Descriptor instead.
func (*ReleaseFundsRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseFundsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReleaseFundsRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReleaseFundsRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *ReleaseFundsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReleaseFundsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseFundsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseFundsResponse) Reset() {
	*x = ReleaseFundsResponse{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseFundsResponse) ProtoMessage() {}

func (x *ReleaseFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseFundsResponse.ProtoReflect.Descriptor instead.
func (*ReleaseFundsResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseFundsResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type RefundFundsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId        int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundFundsRequest) Reset() {
	*x = RefundFundsRequest{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundFundsRequest) ProtoMessage() {}

func (x *RefundFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundFundsRequest.ProtoReflect.Descriptor instead.
func (*RefundFundsRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *RefundFundsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefundFundsRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RefundFundsRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *RefundFundsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RefundFundsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundFundsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Transaction   *domain.LedgerTransaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundFundsResponse) Reset() {
	*x = RefundFundsResponse{}
	mi := &file_v1_order_balance_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundFundsResponse) ProtoMessage() {}

func (x *RefundFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_balance_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundFundsResponse.ProtoReflect.Descriptor instead.
func (*RefundFundsResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_balance_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *RefundFundsResponse) GetTransaction() *domain.LedgerTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_v1_order_balance_order_service_proto protoreflect.FileDescriptor

const file_v1_order_balance_order_service_proto_rawDesc = "" +
	"\n" +
	"$v1/order/balance_order_service.proto\x129github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order\x1a\x1ev1/domain/balance_domain.proto\"\xe3\x01\n" +
	"\x13ReserveFundsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x87\x01\n" +
	"\x14ReserveFundsResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction\"\xe3\x01\n" +
	"\x13CaptureFundsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x87\x01\n" +
	"\x14CaptureFundsResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction\"\xe3\x01\n" +
	"\x13ReleaseFundsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x87\x01\n" +
	"\x14ReleaseFundsResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction\"\xe2\x01\n" +
	"\x12RefundFundsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12W\n" +
	"\x05money\x18\x03 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x86\x01\n" +
	"\x13RefundFundsResponse\x12o\n" +
	"\vtransaction\x18\x01 \x01(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\vtransaction2\xda\x05\n" +
	"\x13BalanceOrderService\x12\xaf\x01\n" +
	"\fReserveFunds\x12N.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsRequest\x1aO.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsResponse\x12\xaf\x01\n" +
	"\fCaptureFunds\x12N.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsRequest\x1aO.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsResponse\x12\xaf\x01\n" +
	"\fReleaseFunds\x12N.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsRequest\x1aO.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsResponse\x12\xac\x01\n" +
	"\vRefundFunds\x12M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsRequest\x1aN.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsResponseBAZ?github.com/martketplace-vkr/balance/pkg/api/grpc/v1/order;orderb\x06proto3"

var (
	file_v1_order_balance_order_service_proto_rawDescOnce sync.Once
	file_v1_order_balance_order_service_proto_rawDescData []byte
)

func file_v1_order_balance_order_service_proto_rawDescGZIP() []byte {
	file_v1_order_balance_order_service_proto_rawDescOnce.Do(func() {
		file_v1_order_balance_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_order_balance_order_service_proto_rawDesc), len(file_v1_order_balance_order_service_proto_rawDesc)))
	})
	return file_v1_order_balance_order_service_proto_rawDescData
}

var file_v1_order_balance_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_order_balance_order_service_proto_goTypes = []any{
	(*ReserveFundsRequest)(nil),      // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsRequest
	(*ReserveFundsResponse)(nil),     // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsResponse
	(*CaptureFundsRequest)(nil),      // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsRequest
	(*CaptureFundsResponse)(nil),     // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsResponse
	(*ReleaseFundsRequest)(nil),      // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsRequest
	(*ReleaseFundsResponse)(nil),     // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsResponse
	(*RefundFundsRequest)(nil),       // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsRequest
	(*RefundFundsResponse)(nil),      // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsResponse
	(*domain.Money)(nil),             // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	(*domain.LedgerTransaction)(nil), // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
}
var file_v1_order_balance_order_service_proto_depIdxs = []int32{
	8,  // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	9,  // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	8,  // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	9,  // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	8,  // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	9,  // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	8,  // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	9,  // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsResponse.transaction:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	0,  // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.ReserveFunds:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsRequest
	2,  // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.CaptureFunds:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsRequest
	4,  // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.ReleaseFunds:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsRequest
	6,  // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.RefundFunds:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsRequest
	1,  // 12: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.ReserveFunds:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReserveFundsResponse
	3,  // 13: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.CaptureFunds:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.CaptureFundsResponse
	5,  // 14: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.ReleaseFunds:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.ReleaseFundsResponse
	7,  // 15: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService.RefundFunds:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.RefundFundsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_order_balance_order_service_proto_init() }
func file_v1_order_balance_order_service_proto_init() {
	if File_v1_order_balance_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_order_balance_order_service_proto_rawDesc), len(file_v1_order_balance_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_order_balance_order_service_proto_goTypes,
		DependencyIndexes: file_v1_order_balance_order_service_proto_depIdxs,
		MessageInfos:      file_v1_order_balance_order_service_proto_msgTypes,
	}.Build()
	File_v1_order_balance_order_service_proto = out.File
	file_v1_order_balance_order_service_proto_goTypes = nil
	file_v1_order_balance_order_service_proto_depIdxs = nil
}
