// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/order/balance_order_service.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceOrderService_ReserveFunds_FullMethodName = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService/ReserveFunds"
	BalanceOrderService_CaptureFunds_FullMethodName = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService/CaptureFunds"
	BalanceOrderService_ReleaseFunds_FullMethodName = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService/ReleaseFunds"
	BalanceOrderService_RefundFunds_FullMethodName  = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService/RefundFunds"
)

// BalanceOrderServiceClient is the client API for BalanceOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceOrderServiceClient interface {
	ReserveFunds(ctx context.Context, in *ReserveFundsRequest, opts ...grpc.CallOption) (*ReserveFundsResponse, error)
	CaptureFunds(ctx context.Context, in *CaptureFundsRequest, opts ...grpc.CallOption) (*CaptureFundsResponse, error)
	ReleaseFunds(ctx context.Context, in *ReleaseFundsRequest, opts ...grpc.CallOption) (*ReleaseFundsResponse, error)
	RefundFunds(ctx context.Context, in *RefundFundsRequest, opts ...grpc.CallOption) (*RefundFundsResponse, error)
}

type balanceOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceOrderServiceClient(cc grpc.ClientConnInterface) BalanceOrderServiceClient {
	return &balanceOrderServiceClient{cc}
}

func (c *balanceOrderServiceClient) ReserveFunds(ctx context.Context, in *ReserveFundsRequest, opts ...grpc.CallOption) (*ReserveFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveFundsResponse)
	err := c.cc.Invoke(ctx, BalanceOrderService_ReserveFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceOrderServiceClient) CaptureFunds(ctx context.Context, in *CaptureFundsRequest, opts ...grpc.CallOption) (*CaptureFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureFundsResponse)
	err := c.cc.Invoke(ctx, BalanceOrderService_CaptureFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceOrderServiceClient) ReleaseFunds(ctx context.Context, in *ReleaseFundsRequest, opts ...grpc.CallOption) (*ReleaseFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseFundsResponse)
	err := c.cc.Invoke(ctx, BalanceOrderService_ReleaseFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceOrderServiceClient) RefundFunds(ctx context.Context, in *RefundFundsRequest, opts ...grpc.CallOption) (*RefundFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundFundsResponse)
	err := c.cc.Invoke(ctx, BalanceOrderService_RefundFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceOrderServiceServer is the server API for BalanceOrderService service.
// All implementations must embed UnimplementedBalanceOrderServiceServer
// for forward compatibility.
type BalanceOrderServiceServer interface {
	ReserveFunds(context.Context, *ReserveFundsRequest) (*ReserveFundsResponse, error)
	CaptureFunds(context.Context, *CaptureFundsRequest) (*CaptureFundsResponse, error)
	ReleaseFunds(context.Context, *ReleaseFundsRequest) (*ReleaseFundsResponse, error)
	RefundFunds(context.Context, *RefundFundsRequest) (*RefundFundsResponse, error)
	mustEmbedUnimplementedBalanceOrderServiceServer()
}

// UnimplementedBalanceOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceOrderServiceServer struct{}

func (UnimplementedBalanceOrderServiceServer) ReserveFunds(context.Context, *ReserveFundsRequest) (*ReserveFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveFunds not implemented")
}
func (UnimplementedBalanceOrderServiceServer) CaptureFunds(context.Context, *CaptureFundsRequest) (*CaptureFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureFunds not implemented")
}
func (UnimplementedBalanceOrderServiceServer) ReleaseFunds(context.Context, *ReleaseFundsRequest) (*ReleaseFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseFunds not implemented")
}
func (UnimplementedBalanceOrderServiceServer) RefundFunds(context.Context, *RefundFundsRequest) (*RefundFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundFunds not implemented")
}
func (UnimplementedBalanceOrderServiceServer) mustEmbedUnimplementedBalanceOrderServiceServer() {}
func (UnimplementedBalanceOrderServiceServer) testEmbeddedByValue()                             {}

// UnsafeBalanceOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceOrderServiceServer will
// result in compilation errors.
type UnsafeBalanceOrderServiceServer interface {
	mustEmbedUnimplementedBalanceOrderServiceServer()
}

func RegisterBalanceOrderServiceServer(s grpc.ServiceRegistrar, srv BalanceOrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedBalanceOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceOrderService_ServiceDesc, srv)
}

func _BalanceOrderService_ReserveFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceOrderServiceServer).ReserveFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceOrderService_ReserveFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceOrderServiceServer).ReserveFunds(ctx, req.(*ReserveFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceOrderService_CaptureFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceOrderServiceServer).CaptureFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceOrderService_CaptureFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceOrderServiceServer).CaptureFunds(ctx, req.(*CaptureFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceOrderService_ReleaseFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceOrderServiceServer).ReleaseFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceOrderService_ReleaseFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceOrderServiceServer).ReleaseFunds(ctx, req.(*ReleaseFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceOrderService_RefundFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceOrderServiceServer).RefundFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceOrderService_RefundFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceOrderServiceServer).RefundFunds(ctx, req.(*RefundFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceOrderService_ServiceDesc is the grpc.ServiceDesc for BalanceOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.martketplace.vkr.balance.pkg.api.grpc.v1.order.BalanceOrderService",
	HandlerType: (*BalanceOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveFunds",
			Handler:    _BalanceOrderService_ReserveFunds_Handler,
		},
		{
			MethodName: "CaptureFunds",
			Handler:    _BalanceOrderService_CaptureFunds_Handler,
		},
		{
			MethodName: "ReleaseFunds",
			Handler:    _BalanceOrderService_ReleaseFunds_Handler,
		},
		{
			MethodName: "RefundFunds",
			Handler:    _BalanceOrderService_RefundFunds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/order/balance_order_service.proto",
}
