// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/client/balance_client_service.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceClientService_GetWallet_FullMethodName             = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/GetWallet"
	BalanceClientService_GetDepositAddressList_FullMethodName = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/GetDepositAddressList"
	BalanceClientService_GetWalletTransactions_FullMethodName = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/GetWalletTransactions"
	BalanceClientService_CreateTopUp_FullMethodName           = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/CreateTopUp"
	BalanceClientService_GetTopUp_FullMethodName              = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/GetTopUp"
	BalanceClientService_GetTopUpList_FullMethodName          = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/GetTopUpList"
	BalanceClientService_CreateWithdrawal_FullMethodName      = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/CreateWithdrawal"
	BalanceClientService_GetWithdrawal_FullMethodName         = "/github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService/GetWithdrawal"
)

// BalanceClientServiceClient is the client API for BalanceClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceClientServiceClient interface {
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	GetDepositAddressList(ctx context.Context, in *GetDepositAddressListRequest, opts ...grpc.CallOption) (*GetDepositAddressListResponse, error)
	GetWalletTransactions(ctx context.Context, in *GetWalletTransactionsRequest, opts ...grpc.CallOption) (*GetWalletTransactionsResponse, error)
	CreateTopUp(ctx context.Context, in *CreateTopUpRequest, opts ...grpc.CallOption) (*CreateTopUpResponse, error)
	GetTopUp(ctx context.Context, in *GetTopUpRequest, opts ...grpc.CallOption) (*GetTopUpResponse, error)
	GetTopUpList(ctx context.Context, in *GetTopUpListRequest, opts ...grpc.CallOption) (*GetTopUpListResponse, error)
	CreateWithdrawal(ctx context.Context, in *CreateWithdrawalRequest, opts ...grpc.CallOption) (*CreateWithdrawalResponse, error)
	GetWithdrawal(ctx context.Context, in *GetWithdrawalRequest, opts ...grpc.CallOption) (*GetWithdrawalResponse, error)
}

type balanceClientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceClientServiceClient(cc grpc.ClientConnInterface) BalanceClientServiceClient {
	return &balanceClientServiceClient{cc}
}

func (c *balanceClientServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClientServiceClient) GetDepositAddressList(ctx context.Context, in *GetDepositAddressListRequest, opts ...grpc.CallOption) (*GetDepositAddressListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositAddressListResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_GetDepositAddressList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClientServiceClient) GetWalletTransactions(ctx context.Context, in *GetWalletTransactionsRequest, opts ...grpc.CallOption) (*GetWalletTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletTransactionsResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_GetWalletTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClientServiceClient) CreateTopUp(ctx context.Context, in *CreateTopUpRequest, opts ...grpc.CallOption) (*CreateTopUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopUpResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_CreateTopUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClientServiceClient) GetTopUp(ctx context.Context, in *GetTopUpRequest, opts ...grpc.CallOption) (*GetTopUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopUpResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_GetTopUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClientServiceClient) GetTopUpList(ctx context.Context, in *GetTopUpListRequest, opts ...grpc.CallOption) (*GetTopUpListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopUpListResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_GetTopUpList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClientServiceClient) CreateWithdrawal(ctx context.Context, in *CreateWithdrawalRequest, opts ...grpc.CallOption) (*CreateWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWithdrawalResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_CreateWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClientServiceClient) GetWithdrawal(ctx context.Context, in *GetWithdrawalRequest, opts ...grpc.CallOption) (*GetWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawalResponse)
	err := c.cc.Invoke(ctx, BalanceClientService_GetWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceClientServiceServer is the server API for BalanceClientService service.
// All implementations must embed UnimplementedBalanceClientServiceServer
// for forward compatibility.
type BalanceClientServiceServer interface {
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	GetDepositAddressList(context.Context, *GetDepositAddressListRequest) (*GetDepositAddressListResponse, error)
	GetWalletTransactions(context.Context, *GetWalletTransactionsRequest) (*GetWalletTransactionsResponse, error)
	CreateTopUp(context.Context, *CreateTopUpRequest) (*CreateTopUpResponse, error)
	GetTopUp(context.Context, *GetTopUpRequest) (*GetTopUpResponse, error)
	GetTopUpList(context.Context, *GetTopUpListRequest) (*GetTopUpListResponse, error)
	CreateWithdrawal(context.Context, *CreateWithdrawalRequest) (*CreateWithdrawalResponse, error)
	GetWithdrawal(context.Context, *GetWithdrawalRequest) (*GetWithdrawalResponse, error)
	mustEmbedUnimplementedBalanceClientServiceServer()
}

// UnimplementedBalanceClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceClientServiceServer struct{}

func (UnimplementedBalanceClientServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedBalanceClientServiceServer) GetDepositAddressList(context.Context, *GetDepositAddressListRequest) (*GetDepositAddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositAddressList not implemented")
}
func (UnimplementedBalanceClientServiceServer) GetWalletTransactions(context.Context, *GetWalletTransactionsRequest) (*GetWalletTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletTransactions not implemented")
}
func (UnimplementedBalanceClientServiceServer) CreateTopUp(context.Context, *CreateTopUpRequest) (*CreateTopUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopUp not implemented")
}
func (UnimplementedBalanceClientServiceServer) GetTopUp(context.Context, *GetTopUpRequest) (*GetTopUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUp not implemented")
}
func (UnimplementedBalanceClientServiceServer) GetTopUpList(context.Context, *GetTopUpListRequest) (*GetTopUpListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUpList not implemented")
}
func (UnimplementedBalanceClientServiceServer) CreateWithdrawal(context.Context, *CreateWithdrawalRequest) (*CreateWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWithdrawal not implemented")
}
func (UnimplementedBalanceClientServiceServer) GetWithdrawal(context.Context, *GetWithdrawalRequest) (*GetWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawal not implemented")
}
func (UnimplementedBalanceClientServiceServer) mustEmbedUnimplementedBalanceClientServiceServer() {}
func (UnimplementedBalanceClientServiceServer) testEmbeddedByValue()                              {}

// UnsafeBalanceClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceClientServiceServer will
// result in compilation errors.
type UnsafeBalanceClientServiceServer interface {
	mustEmbedUnimplementedBalanceClientServiceServer()
}

func RegisterBalanceClientServiceServer(s grpc.ServiceRegistrar, srv BalanceClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedBalanceClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceClientService_ServiceDesc, srv)
}

func _BalanceClientService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceClientService_GetDepositAddressList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositAddressListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).GetDepositAddressList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_GetDepositAddressList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).GetDepositAddressList(ctx, req.(*GetDepositAddressListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceClientService_GetWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).GetWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_GetWalletTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).GetWalletTransactions(ctx, req.(*GetWalletTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceClientService_CreateTopUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).CreateTopUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_CreateTopUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).CreateTopUp(ctx, req.(*CreateTopUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceClientService_GetTopUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).GetTopUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_GetTopUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).GetTopUp(ctx, req.(*GetTopUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceClientService_GetTopUpList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopUpListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).GetTopUpList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_GetTopUpList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).GetTopUpList(ctx, req.(*GetTopUpListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceClientService_CreateWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).CreateWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_CreateWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).CreateWithdrawal(ctx, req.(*CreateWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceClientService_GetWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceClientServiceServer).GetWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceClientService_GetWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceClientServiceServer).GetWithdrawal(ctx, req.(*GetWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceClientService_ServiceDesc is the grpc.ServiceDesc for BalanceClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService",
	HandlerType: (*BalanceClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWallet",
			Handler:    _BalanceClientService_GetWallet_Handler,
		},
		{
			MethodName: "GetDepositAddressList",
			Handler:    _BalanceClientService_GetDepositAddressList_Handler,
		},
		{
			MethodName: "GetWalletTransactions",
			Handler:    _BalanceClientService_GetWalletTransactions_Handler,
		},
		{
			MethodName: "CreateTopUp",
			Handler:    _BalanceClientService_CreateTopUp_Handler,
		},
		{
			MethodName: "GetTopUp",
			Handler:    _BalanceClientService_GetTopUp_Handler,
		},
		{
			MethodName: "GetTopUpList",
			Handler:    _BalanceClientService_GetTopUpList_Handler,
		},
		{
			MethodName: "CreateWithdrawal",
			Handler:    _BalanceClientService_CreateWithdrawal_Handler,
		},
		{
			MethodName: "GetWithdrawal",
			Handler:    _BalanceClientService_GetWithdrawal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/client/balance_client_service.proto",
}
