// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/client/balance_client_service.proto

package client

import (
	domain "github.com/martketplace-vkr/balance/pkg/api/grpc/v1/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *domain.Wallet         `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletResponse) GetWallet() *domain.Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type GetDepositAddressListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositAddressListRequest) Reset() {
	*x = GetDepositAddressListRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositAddressListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositAddressListRequest) ProtoMessage() {}

func (x *GetDepositAddressListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositAddressListRequest.ProtoReflect.Descriptor instead.
func (*GetDepositAddressListRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDepositAddressListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetDepositAddressListResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	DepositAddresses []*domain.DepositAddress `protobuf:"bytes,1,rep,name=deposit_addresses,json=depositAddresses,proto3" json:"deposit_addresses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDepositAddressListResponse) Reset() {
	*x = GetDepositAddressListResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositAddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositAddressListResponse) ProtoMessage() {}

func (x *GetDepositAddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositAddressListResponse.ProtoReflect.Descriptor instead.
func (*GetDepositAddressListResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepositAddressListResponse) GetDepositAddresses() []*domain.DepositAddress {
	if x != nil {
		return x.DepositAddresses
	}
	return nil
}

type GetWalletTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyCode  *int64                 `protobuf:"varint,2,opt,name=currency_code,json=currencyCode,proto3,oneof" json:"currency_code,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletTransactionsRequest) Reset() {
	*x = GetWalletTransactionsRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTransactionsRequest) ProtoMessage() {}

func (x *GetWalletTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletTransactionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetCurrencyCode() int64 {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWalletTransactionsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetWalletTransactionsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Transactions  []*domain.LedgerTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletTransactionsResponse) Reset() {
	*x = GetWalletTransactionsResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletTransactionsResponse) ProtoMessage() {}

func (x *GetWalletTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetWalletTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetWalletTransactionsResponse) GetTransactions() []*domain.LedgerTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CreateTopUpRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Money          *domain.Money          `protobuf:"bytes,2,opt,name=money,proto3" json:"money,omitempty"`
	ProviderType   domain.ProviderType    `protobuf:"varint,3,opt,name=provider_type,json=providerType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType" json:"provider_type,omitempty"`
	ProviderName   string                 `protobuf:"bytes,4,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SuccessUrl     string                 `protobuf:"bytes,6,opt,name=success_url,json=successUrl,proto3" json:"success_url,omitempty"`
	FailUrl        string                 `protobuf:"bytes,7,opt,name=fail_url,json=failUrl,proto3" json:"fail_url,omitempty"`
	Network        *string                `protobuf:"bytes,8,opt,name=network,proto3,oneof" json:"network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTopUpRequest) Reset() {
	*x = CreateTopUpRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopUpRequest) ProtoMessage() {}

func (x *CreateTopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopUpRequest.ProtoReflect.Descriptor instead.
func (*CreateTopUpRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTopUpRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTopUpRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *CreateTopUpRequest) GetProviderType() domain.ProviderType {
	if x != nil {
		return x.ProviderType
	}
	return domain.ProviderType(0)
}

func (x *CreateTopUpRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *CreateTopUpRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateTopUpRequest) GetSuccessUrl() string {
	if x != nil {
		return x.SuccessUrl
	}
	return ""
}

func (x *CreateTopUpRequest) GetFailUrl() string {
	if x != nil {
		return x.FailUrl
	}
	return ""
}

func (x *CreateTopUpRequest) GetNetwork() string {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return ""
}

type CreateTopUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopUp         *domain.TopUp          `protobuf:"bytes,1,opt,name=top_up,json=topUp,proto3" json:"top_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopUpResponse) Reset() {
	*x = CreateTopUpResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopUpResponse) ProtoMessage() {}

func (x *CreateTopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopUpResponse.ProtoReflect.Descriptor instead.
func (*CreateTopUpResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTopUpResponse) GetTopUp() *domain.TopUp {
	if x != nil {
		return x.TopUp
	}
	return nil
}

type GetTopUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopUpId       int64                  `protobuf:"varint,2,opt,name=top_up_id,json=topUpId,proto3" json:"top_up_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUpRequest) Reset() {
	*x = GetTopUpRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUpRequest) ProtoMessage() {}

func (x *GetTopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUpRequest.ProtoReflect.Descriptor instead.
func (*GetTopUpRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopUpRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTopUpRequest) GetTopUpId() int64 {
	if x != nil {
		return x.TopUpId
	}
	return 0
}

type GetTopUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopUp         *domain.TopUp          `protobuf:"bytes,1,opt,name=top_up,json=topUp,proto3" json:"top_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUpResponse) Reset() {
	*x = GetTopUpResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUpResponse) ProtoMessage() {}

func (x *GetTopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUpResponse.ProtoReflect.Descriptor instead.
func (*GetTopUpResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetTopUpResponse) GetTopUp() *domain.TopUp {
	if x != nil {
		return x.TopUp
	}
	return nil
}

type GetTopUpListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUpListRequest) Reset() {
	*x = GetTopUpListRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUpListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUpListRequest) ProtoMessage() {}

func (x *GetTopUpListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUpListRequest.ProtoReflect.Descriptor instead.
func (*GetTopUpListRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetTopUpListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTopUpListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopUpListRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTopUpListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopUps        []*domain.TopUp        `protobuf:"bytes,1,rep,name=top_ups,json=topUps,proto3" json:"top_ups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUpListResponse) Reset() {
	*x = GetTopUpListResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUpListResponse) ProtoMessage() {}

func (x *GetTopUpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUpListResponse.ProtoReflect.Descriptor instead.
func (*GetTopUpListResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetTopUpListResponse) GetTopUps() []*domain.TopUp {
	if x != nil {
		return x.TopUps
	}
	return nil
}

type CreateWithdrawalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Money           *domain.Money          `protobuf:"bytes,2,opt,name=money,proto3" json:"money,omitempty"`
	DestinationType domain.DestinationType `protobuf:"varint,3,opt,name=destination_type,json=destinationType,proto3,enum=github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationType" json:"destination_type,omitempty"`
	Destination     string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWithdrawalRequest) Reset() {
	*x = CreateWithdrawalRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawalRequest) ProtoMessage() {}

func (x *CreateWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*CreateWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateWithdrawalRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateWithdrawalRequest) GetMoney() *domain.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *CreateWithdrawalRequest) GetDestinationType() domain.DestinationType {
	if x != nil {
		return x.DestinationType
	}
	return domain.DestinationType(0)
}

func (x *CreateWithdrawalRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateWithdrawalRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawal    *domain.Withdrawal     `protobuf:"bytes,1,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWithdrawalResponse) Reset() {
	*x = CreateWithdrawalResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithdrawalResponse) ProtoMessage() {}

func (x *CreateWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*CreateWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateWithdrawalResponse) GetWithdrawal() *domain.Withdrawal {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

type GetWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WithdrawalId  int64                  `protobuf:"varint,2,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalRequest) Reset() {
	*x = GetWithdrawalRequest{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalRequest) ProtoMessage() {}

func (x *GetWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*GetWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetWithdrawalRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetWithdrawalRequest) GetWithdrawalId() int64 {
	if x != nil {
		return x.WithdrawalId
	}
	return 0
}

type GetWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawal    *domain.Withdrawal     `protobuf:"bytes,1,opt,name=withdrawal,proto3" json:"withdrawal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWithdrawalResponse) Reset() {
	*x = GetWithdrawalResponse{}
	mi := &file_v1_client_balance_client_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWithdrawalResponse) ProtoMessage() {}

func (x *GetWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_balance_client_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*GetWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_balance_client_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetWithdrawalResponse) GetWithdrawal() *domain.Withdrawal {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

var File_v1_client_balance_client_service_proto protoreflect.FileDescriptor

const file_v1_client_balance_client_service_proto_rawDesc = "" +
	"\n" +
	"&v1/client/balance_client_service.proto\x12:github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client\x1a\x1ev1/domain/balance_domain.proto\"+\n" +
	"\x10GetWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"o\n" +
	"\x11GetWalletResponse\x12Z\n" +
	"\x06wallet\x18\x01 \x01(\v2B.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WalletR\x06wallet\"7\n" +
	"\x1cGetDepositAddressListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x98\x01\n" +
	"\x1dGetDepositAddressListResponse\x12w\n" +
	"\x11deposit_addresses\x18\x01 \x03(\v2J.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DepositAddressR\x10depositAddresses\"\xa1\x01\n" +
	"\x1cGetWalletTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\rcurrency_code\x18\x02 \x01(\x03H\x00R\fcurrencyCode\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offsetB\x10\n" +
	"\x0e_currency_code\"\x92\x01\n" +
	"\x1dGetWalletTransactionsResponse\x12q\n" +
	"\ftransactions\x18\x01 \x03(\v2M.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransactionR\ftransactions\"\xaa\x03\n" +
	"\x12CreateTopUpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12W\n" +
	"\x05money\x18\x02 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12m\n" +
	"\rprovider_type\x18\x03 \x01(\x0e2H.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderTypeR\fproviderType\x12#\n" +
	"\rprovider_name\x18\x04 \x01(\tR\fproviderName\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\vsuccess_url\x18\x06 \x01(\tR\n" +
	"successUrl\x12\x19\n" +
	"\bfail_url\x18\a \x01(\tR\afailUrl\x12\x1d\n" +
	"\anetwork\x18\b \x01(\tH\x00R\anetwork\x88\x01\x01B\n" +
	"\n" +
	"\b_network\"o\n" +
	"\x13CreateTopUpResponse\x12X\n" +
	"\x06top_up\x18\x01 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpR\x05topUp\"F\n" +
	"\x0fGetTopUpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\ttop_up_id\x18\x02 \x01(\x03R\atopUpId\"l\n" +
	"\x10GetTopUpResponse\x12X\n" +
	"\x06top_up\x18\x01 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpR\x05topUp\"\\\n" +
	"\x13GetTopUpListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"r\n" +
	"\x14GetTopUpListResponse\x12Z\n" +
	"\atop_ups\x18\x01 \x03(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUpR\x06topUps\"\xce\x02\n" +
	"\x17CreateWithdrawalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12W\n" +
	"\x05money\x18\x02 \x01(\v2A.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.MoneyR\x05money\x12v\n" +
	"\x10destination_type\x18\x03 \x01(\x0e2K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationTypeR\x0fdestinationType\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\x82\x01\n" +
	"\x18CreateWithdrawalResponse\x12f\n" +
	"\n" +
	"withdrawal\x18\x01 \x01(\v2F.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WithdrawalR\n" +
	"withdrawal\"T\n" +
	"\x14GetWithdrawalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rwithdrawal_id\x18\x02 \x01(\x03R\fwithdrawalId\"\x7f\n" +
	"\x15GetWithdrawalResponse\x12f\n" +
	"\n" +
	"withdrawal\x18\x01 \x01(\v2F.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.WithdrawalR\n" +
	"withdrawal2\xe3\v\n" +
	"\x14BalanceClientService\x12\xa8\x01\n" +
	"\tGetWallet\x12L.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletRequest\x1aM.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletResponse\x12\xcc\x01\n" +
	"\x15GetDepositAddressList\x12X.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetDepositAddressListRequest\x1aY.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetDepositAddressListResponse\x12\xcc\x01\n" +
	"\x15GetWalletTransactions\x12X.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletTransactionsRequest\x1aY.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletTransactionsResponse\x12\xae\x01\n" +
	"\vCreateTopUp\x12N.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpRequest\x1aO.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpResponse\x12\xa5\x01\n" +
	"\bGetTopUp\x12K.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpRequest\x1aL.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpResponse\x12\xb1\x01\n" +
	"\fGetTopUpList\x12O.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpListRequest\x1aP.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpListResponse\x12\xbd\x01\n" +
	"\x10CreateWithdrawal\x12S.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalRequest\x1aT.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalResponse\x12\xb4\x01\n" +
	"\rGetWithdrawal\x12P.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWithdrawalRequest\x1aQ.github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWithdrawalResponseBCZAgithub.com/martketplace-vkr/balance/pkg/api/grpc/v1/client;clientb\x06proto3"

var (
	file_v1_client_balance_client_service_proto_rawDescOnce sync.Once
	file_v1_client_balance_client_service_proto_rawDescData []byte
)

func file_v1_client_balance_client_service_proto_rawDescGZIP() []byte {
	file_v1_client_balance_client_service_proto_rawDescOnce.Do(func() {
		file_v1_client_balance_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_client_balance_client_service_proto_rawDesc), len(file_v1_client_balance_client_service_proto_rawDesc)))
	})
	return file_v1_client_balance_client_service_proto_rawDescData
}

var file_v1_client_balance_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_client_balance_client_service_proto_goTypes = []any{
	(*GetWalletRequest)(nil),              // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletRequest
	(*GetWalletResponse)(nil),             // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletResponse
	(*GetDepositAddressListRequest)(nil),  // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetDepositAddressListRequest
	(*GetDepositAddressListResponse)(nil), // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetDepositAddressListResponse
	(*GetWalletTransactionsRequest)(nil),  // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletTransactionsRequest
	(*GetWalletTransactionsResponse)(nil), // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletTransactionsResponse
	(*CreateTopUpRequest)(nil),            // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpRequest
	(*CreateTopUpResponse)(nil),           // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpResponse
	(*GetTopUpRequest)(nil),               // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpRequest
	(*GetTopUpResponse)(nil),              // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpResponse
	(*GetTopUpListRequest)(nil),           // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpListRequest
	(*GetTopUpListResponse)(nil),          // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpListResponse
	(*CreateWithdrawalRequest)(nil),       // 12: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalRequest
	(*CreateWithdrawalResponse)(nil),      // 13: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalResponse
	(*GetWithdrawalRequest)(nil),          // 14: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWithdrawalRequest
	(*GetWithdrawalResponse)(nil),         // 15: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWithdrawalResponse
	(*domain.Wallet)(nil),                 // 16: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet
	(*domain.DepositAddress)(nil),         // 17: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DepositAddress
	(*domain.LedgerTransaction)(nil),      // 18: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	(*domain.Money)(nil),                  // 19: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	(domain.ProviderType)(0),              // 20: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType
	(*domain.TopUp)(nil),                  // 21: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
	(domain.DestinationType)(0),           // 22: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationType
	(*domain.Withdrawal)(nil),             // 23: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal
}
var file_v1_client_balance_client_service_proto_depIdxs = []int32{
	16, // 0: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletResponse.wallet:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet
	17, // 1: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetDepositAddressListResponse.deposit_addresses:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DepositAddress
	18, // 2: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletTransactionsResponse.transactions:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction
	19, // 3: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	20, // 4: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpRequest.provider_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType
	21, // 5: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpResponse.top_up:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
	21, // 6: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpResponse.top_up:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
	21, // 7: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpListResponse.top_ups:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp
	19, // 8: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalRequest.money:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money
	22, // 9: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalRequest.destination_type:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationType
	23, // 10: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalResponse.withdrawal:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal
	23, // 11: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWithdrawalResponse.withdrawal:type_name -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal
	0,  // 12: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetWallet:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletRequest
	2,  // 13: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetDepositAddressList:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetDepositAddressListRequest
	4,  // 14: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetWalletTransactions:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletTransactionsRequest
	6,  // 15: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.CreateTopUp:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpRequest
	8,  // 16: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetTopUp:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpRequest
	10, // 17: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetTopUpList:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpListRequest
	12, // 18: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.CreateWithdrawal:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalRequest
	14, // 19: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetWithdrawal:input_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWithdrawalRequest
	1,  // 20: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetWallet:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletResponse
	3,  // 21: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetDepositAddressList:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetDepositAddressListResponse
	5,  // 22: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetWalletTransactions:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWalletTransactionsResponse
	7,  // 23: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.CreateTopUp:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateTopUpResponse
	9,  // 24: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetTopUp:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpResponse
	11, // 25: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetTopUpList:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetTopUpListResponse
	13, // 26: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.CreateWithdrawal:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.CreateWithdrawalResponse
	15, // 27: github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.BalanceClientService.GetWithdrawal:output_type -> github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client.GetWithdrawalResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_client_balance_client_service_proto_init() }
func file_v1_client_balance_client_service_proto_init() {
	if File_v1_client_balance_client_service_proto != nil {
		return
	}
	file_v1_client_balance_client_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_v1_client_balance_client_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_client_balance_client_service_proto_rawDesc), len(file_v1_client_balance_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_client_balance_client_service_proto_goTypes,
		DependencyIndexes: file_v1_client_balance_client_service_proto_depIdxs,
		MessageInfos:      file_v1_client_balance_client_service_proto_msgTypes,
	}.Build()
	File_v1_client_balance_client_service_proto = out.File
	file_v1_client_balance_client_service_proto_goTypes = nil
	file_v1_client_balance_client_service_proto_depIdxs = nil
}
