syntax = "proto3";

package github.com.martketplace.vkr.balance.pkg.api.grpc.v1.client;

import "v1/domain/balance_domain.proto";

option go_package = "github.com/martketplace-vkr/balance/pkg/api/grpc/v1/client;client";

service BalanceClientService {
  rpc GetWallet(GetWalletRequest) returns (GetWalletResponse);
  rpc GetDepositAddressList(GetDepositAddressListRequest) returns (GetDepositAddressListResponse);
  rpc GetWalletTransactions(GetWalletTransactionsRequest) returns (GetWalletTransactionsResponse);
  rpc CreateTopUp(CreateTopUpRequest) returns (CreateTopUpResponse);
  rpc GetTopUp(GetTopUpRequest) returns (GetTopUpResponse);
  rpc GetTopUpList(GetTopUpListRequest) returns (GetTopUpListResponse);
  rpc CreateWithdrawal(CreateWithdrawalRequest) returns (CreateWithdrawalResponse);
  rpc GetWithdrawal(GetWithdrawalRequest) returns (GetWithdrawalResponse);
}

message GetWalletRequest {
  int64 user_id = 1;
}

message GetWalletResponse {
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Wallet wallet = 1;
}

message GetDepositAddressListRequest {
  int64 user_id = 1;
}

message GetDepositAddressListResponse {
  repeated .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DepositAddress deposit_addresses = 1;
}

message GetWalletTransactionsRequest {
  int64 user_id = 1;
  optional int64 currency_code = 2;
  uint32 limit = 3;
  uint64 offset = 4;
}

message GetWalletTransactionsResponse {
  repeated .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.LedgerTransaction transactions = 1;
}

message CreateTopUpRequest {
  int64 user_id = 1;
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money money = 2;
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.ProviderType provider_type = 3;
  string provider_name = 4;
  string idempotency_key = 5;
  string success_url = 6;
  string fail_url = 7;
  optional string network = 8;
}

message CreateTopUpResponse {
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp top_up = 1;
}

message GetTopUpRequest {
  int64 user_id = 1;
  int64 top_up_id = 2;
}

message GetTopUpResponse {
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp top_up = 1;
}

message GetTopUpListRequest {
  int64 user_id = 1;
  uint32 limit = 2;
  uint64 offset = 3;
}

message GetTopUpListResponse {
  repeated .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.TopUp top_ups = 1;
}

message CreateWithdrawalRequest {
  int64 user_id = 1;
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Money money = 2;
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.DestinationType destination_type = 3;
  string destination = 4;
  string idempotency_key = 5;
}

message CreateWithdrawalResponse {
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal withdrawal = 1;
}

message GetWithdrawalRequest {
  int64 user_id = 1;
  int64 withdrawal_id = 2;
}

message GetWithdrawalResponse {
  .github.com.martketplace.vkr.balance.pkg.api.grpc.v1.domain.Withdrawal withdrawal = 1;
}
